### ISSUE TITLE
How to upload to s3 with the correct content-type

### ISSUE THREAD

**Issue by sngmn451** [sor4chi/hono-storage#69]
Hi I've a problem with the S3, and I've explored the docs and couldn't find where to config it.
The file uploaded always type `application/octet-stream` whatever the file content-type it is. It's always `application/octet-stream`.

<img width="395" alt="image" src="https://github.com/user-attachments/assets/b5762210-c709-41ff-8d83-05315f60c238">

My middleware:
```typescript
export const s3storageMiddleware = new HonoS3Storage({
  key(context, file) {
    const { path } = context.req.param()
    const key = `${path ? `${path}/` : ""}${slugify(file.originalname, {
      lower: true,
      strict: true,
    })}-${Date.now()}.${file.extension}`
    context.set("s3UploadedFileKey", key)
    return key
  },
  bucket: (context) => context.env.S3_BUCKET,
  client: (context) => createS3Client(context),
})
```

Did I do something wrong?
Thanks in advance.

**Comment by sngmn451** [comment]
More context.
I used uppy for upload and I've verified that the content type in fetch request is correct.
<img width="149" alt="image" src="https://github.com/user-attachments/assets/68eadee8-b5ba-44df-bd26-475344b9c472">

**Comment by sngmn451** [comment]
Look like when I logged out the file type from `packages/s3/src/storage.ts` the type is missing
<img width="365" alt="image" src="https://github.com/user-attachments/assets/27a373c4-96b6-4af5-9f65-19f049be688b">

**Comment by sor4chi** [comment]
thank you for contributing!
